services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - CSV_PATH=data/healthcare_dataset.csv
      - DB_URL=postgresql+psycopg2://etl_user:etl_pass@db:5432/etl_db

volumes:
  pgdata:
